### ISSUE TITLE
[question] Have pre-releases/nightly/dev builds

### ISSUE THREAD

**Issue by maksym-nazarenko** [ddelnano/terraform-provider-mikrotik#107]
Hi @ddelnano , what do you think about having another channel with more frequent releases so community can give feedback in shorter cycles?

Like having pre-releases which are [supported](https://www.terraform.io/registry/providers/publishing#creating-a-github-release) in registry.

I know I can always build one locally but living on bleeding edge from official registry eliminates errors like issues with local Go installation.

WDYT?

**Comment by ddelnano** [comment]
That sounds great, so no concerns with the idea of it.

**Comment by maksym-nazarenko** [comment]
Since it is not easily possible to have nightly builds (Terraform registry requires releases anyway, and I am not a big fan of polluting repo history), I decided to add section to Readme with instructions about building the provider locally

Should be closed by GH-120
