### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by connorhsm** [ddelnano/terraform-provider-mikrotik#124]
Can a license please be added to this repository to clarify the terms of use? https://choosealicense.com/

**Comment by ddelnano** [comment]
@maksym-nazarenko any preferences? I typically do MIT to be permissive and simple, but open to whatever thoughts you have.

**Comment by maksym-nazarenko** [comment]
@ddelnano I mostly use `Apache2` or `MIT` license in my projects. The most recent are using `MIT`, so I give my thumbs up for the latter.

**Comment by ddelnano** [comment]
@connorhsm the license was added in dfc21a44d691d2cc508892b32f1a872b76e6480b. Thanks for calling this out!
