### ISSUE TITLE
Create `mikrotik_interface_wireguard` resource

### ISSUE THREAD

**Issue by ddelnano** [ddelnano/terraform-provider-mikrotik#137]
This is the first step of Wireguard support. We need to be able to create Wireguard interfaces which are controlled via the `/interface/wireguard add` cli command.

**Comment by jdelnano** [comment]
With the changes in https://github.com/ddelnano/terraform-provider-mikrotik/pull/153 being pulled into https://github.com/ddelnano/terraform-provider-mikrotik/pull/159 and getting merged, this issue is now closed.
