### ISSUE TITLE
Create `mikrotik_wireguard_peer` resource

### ISSUE THREAD

**Issue by ddelnano** [ddelnano/terraform-provider-mikrotik#138]
Once the `mikrotik_interface_wireguard` resource is supported, we will want to be able to add peers. These are created via the `/interface/wireguard/peers add` cli command.

**Comment by maksym-nazarenko** [comment]
@ddelnano is this resolved by #176 or I'm missing something?

**Comment by jdelnano** [comment]
> @ddelnano is this resolved by #176 or I'm missing something?

@maksym-nazarenko yes, this issue is resolved now!
