### ISSUE TITLE
Resource imports using internal IDs required upper case hex digits

### ISSUE THREAD

**Issue by ddelnano** [ddelnano/terraform-provider-mikrotik#144]
I am running into an issue where I'm unable to import a `mikrotik_dhcp_lease` resource. The current functionality works by importing the resource with the Mikortik internal ID. This can be found through the following command:

```
[admin@MikroTik] /ip/dhcp-server/lease> :put [find where address=192.168.88.35]
*6859

[admin@MikroTik] /ip/dhcp-server/lease> :put [find where address=192.168.88.64]
*83c1
```

Note that these values are hexadecimal values, however, the first one is made of purely decimal characters. The second contains an exclusively hexadecimal digit (the **c** in `*83c1`).

The former ID works when importing a dhcp resource, while the latter does not.

```
ddelnano@ddelnano-desktop:~/code/terraform$ terraform import mikrotik_dhcp_lease.tfer--xcp-002D-ng-002D-nested-002D--002A-6859  '*6859'
mikrotik_dhcp_lease.tfer--xcp-002D-ng-002D-nested-002D--002A-6859: Importing from ID "*6859"...
mikrotik_dhcp_lease.tfer--xcp-002D-ng-002D-nested-002D--002A-6859: Import prepared!
  Prepared mikrotik_dhcp_lease for import
mikrotik_dhcp_lease.tfer--xcp-002D-ng-002D-nested-002D--002A-6859: Refreshing state... [id=*6859]

[ .. ]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.


ddelnano@ddelnano-desktop:~/code/terraform$ terraform import mikrotik_dhcp_lease.tfer--k8s-002D--002A-83C1  '*83c1'
mikrotik_dhcp_lease.tfer--k8s-002D--002A-83C1: Importing from ID "*83c1"...
mikrotik_dhcp_lease.tfer--k8s-002D--002A-83C1: Import prepared!
  Prepared mikrotik_dhcp_lease for import

 [ ... ]

│ Error: Cannot import non-existent remote object
│
│ While attempting to import an existing object to "mikrotik_dhcp_lease.tfer--k8s-002D--002A-83C1", the provider detected that no object exists with the given id. Only pre-existing objects can be imported; check
│ that the id is correct and that it is associated with the provider's configured region or endpoint, or use "terraform apply" to create a new remote object for this resource.
╵
```

My current theory is that the presence of hexadecimal digits is the source of this, but more confirmation is needed. If this ends up being the case, then this bug likely applies to all resource imports that allow Mikoritik's internal `.id`.

**Comment by maksym-nazarenko** [comment]
@ddelnano can you try importing with all uppercase, e.g.: `terraform import mikrotik_dhcp_lease.tfer--k8s-002D--002A-83C1  '*83C1'` (with uppercase `C`)?

**Comment by ddelnano** [comment]
@maksym-nazarenko that was it!

I don't believe our documentation mentions this assumption, so it would be good to document what the expected format is. Another thing we could consider is updating the import logic to perform upper case characters so that it works in both cases.

**Comment by maksym-nazarenko** [comment]
yes, documentation must be updated (I can't remember why I didn't do that when I faced the same issue).
I think, a bit of confusion brings MikroTik's CLI, where it prints IDs in lowercase, but refuses to search for the object with the same ID 🤷 

Could you add a task to this issue to update the documentation/logic in code, so it is not lost afterwards?
