### ISSUE TITLE
Automatic change log (release notes) generation

### ISSUE THREAD

**Issue by ddelnano** [ddelnano/terraform-provider-mikrotik#149]
Having automatic change log (or release note generation) would further streamline the release process. It's been ~6 months since the latest release and I think having this capability would make the release process more frequent.

@maksym-nazarenko correct me if I'm wrong, but I thought you expressed interest in this idea before. What are your thoughts about using a tool and some convention for commit messages to make generating these updates easy?

I did some light research and saw the following projects support this type of generation:
- [git-cliif](https://git-cliff.org/)
- [goreleaser](https://goreleaser.com/customization/changelog/) (benefit is that this is a tool already in use)
- [github-changelog-generator](https://github.com/github-changelog-generator/github-changelog-generator)
- [GitHub's change log functionality](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes)

Open to ideas on what we should use, although it does seem convenient to piggy back off our existing usage of goreleaser.

**Comment by maksym-nazarenko** [comment]
@ddelnano I vote for using already available tools (unless you have strong arguments to introduce something new 😀  )
I've played with different [backend implementations](https://goreleaser.com/customization/changelog/) in `goreleaser` [here](https://github.com/maksym-nazarenko/proxx-game/blob/8e2553dd888a9237e249bb88b2d59679e589d3d3/.goreleaser.yml#L44).

From my perspective, using built-in implementation of `goreleaser` grouping, that requires usage of `regexp` and proper formatting of your commit messages, could be not obvious and easy to forget.

Using `github-native` grouping via `labels` seems easier to me, as you always can assign/change label for PR just before pushing new tag (didn't try this feature yet).

My opinion is that `github-native` should be fine as first step (I'm still flexible to take another approach, unless it brings more troubles than benefits...)

Whatever we choose, I can support you in testing and share the results in this thread.

**Comment by ddelnano** [comment]
The `github-native` option sounds good to me. I really just want something that's easy to use, so I also have a preference for not introducing anything new (unless it brings significant benefits).

**Comment by ddelnano** [comment]
@maksym-nazarenko let me know how the release notes below look to you. If they are good, then I will update our github release publishing to be automatic (as described here) and publish the next release 🎉.

![Screen Shot 2023-05-10 at 8 10 23 PM](https://github.com/ddelnano/terraform-provider-mikrotik/assets/5855593/40272f25-65ed-4f15-a033-916dc850b830)

**Comment by ddelnano** [comment]
The release publishing process is automatic as of #155, so this is complete!
