### ISSUE TITLE
RouterOS container fails to start in actions

### ISSUE THREAD

**Issue by maksym-nazarenko** [ddelnano/terraform-provider-mikrotik#224]
Tests [fail](https://github.com/ddelnano/terraform-provider-mikrotik/actions/runs/8054509931/job/22047319621?pr=222) for the latest RouterOS container.

Running `qemu-system-x86_64` fails with error:
```
$ qemu-system-x86_64 -serial mon:stdio -nographic -m 512 -smp 4,sockets=1,cores=4,threads=1 -cpu host -nic tap,id=qemu1,mac=54:05:AB:CD:12:31,script=/routeros/qemu-ifup,downscript=/routeros/qemu-ifdown -hda chr-7.13.5.vdi

qemu-system-x86_64: CPU model 'host' requires KVM or HVF
```

If `-cpu host` is removed from the command it works.

Update (@maksym-nazarenko), 2024-06-23
It is a breaking-chnage in the upstream that prevents using the images on non KVM-enabled systems.
See #232 for a local environment fix which will be expanded to GH actions as well.

**Comment by ddelnano** [comment]
When you say there is a breaking change upstream are you talking about within the https://github.com/EvilFreelancer/docker-routeros project? If so, have you considered making that project's docker image more runtime configurable (allowing `-cpu` to be overridden)?

**Comment by maksym-nazarenko** [comment]
@ddelnano yes, I'm talking about that project.
The fix is relatively easy, but considering the origin of that project, I'l rather spend week integrating another solution that contributing to upstream.

The `qemu-docker` project seems mature and configurable to me (it's even possible to access the VM via VNC in your browser to debug :) )

Anyway, it's up to you to make a decision here - I'm just making a proposal for the change.

**Comment by ddelnano** [comment]
Thanks for the background. I'm ok with moving forward with that, just want to make sure I understand the situation :)
