### ISSUE TITLE
Outdated provider version in terraform registry

### ISSUE THREAD

**Issue by ermyril** [ddelnano/terraform-provider-mikrotik#233]
Hi guys!
I've noticed that it seems impossible to get v0.16.0 from [terraform registry](https://registry.terraform.io/providers/ddelnano/mikrotik/), the latest version is 0.15.0
Is it expected and just part of a release process or you can update it?

It seems that the only option for using latest version at the moment is to build it locally? or is it possible to somehow point terraform to github?

Thank you

**Comment by maksym-nazarenko** [comment]
hey @ermyril you are right - the only way to use `master` branch is to build it locally.
We already had this discussion in #107 but Terraform registry does not allow any `-beta` or `nightly` builds.

There are several ways how we can handle this.
One way, that is impelmented, is to build it locally - but requires Go to be installed.

As of other possible improvements, I see:
1. Build it locally in container (requires Docker to be installed and use custom tfrc file)
2. Introduce `nightly` mode, let's say via changing current terraform config file to custom, which pulls provider from different repo (requires changes in CI to push nightly builds somewhere)

@ermyril @ddelnano wdyt about it?

**Comment by ermyril** [comment]
@maksym-nazarenko, thank you for such a timely reply!

I don't think that building a golang app is such a big deal to bother with docker tbh, I was able to build it in just a few minutes, easier than a nodejs
Second option looks better, but I'm concerned that the effort involved may not be justified by the benefits

I'll reiterate my original question though:
Currently in github in releases there is a  v0.16.0, it doesn't look like a nightly or beta
But the latest available release in terraform registry is v0.15.0

It seems like the latest release just didn't make it to the registry for some reason, even though it happened a few months ago

**Comment by maksym-nazarenko** [comment]
indeed, the release job failed
@ddelnano the `release` action failed due to expired primary (GPG?) key - could you take a look when you have a minute, please?

**Comment by ddelnano** [comment]
Sorry for the delay! v0.16.1 is available now. The new GPG key will be good for 2 years.
