### ISSUE TITLE
mikrotik_pool resource missing documentation

### ISSUE THREAD

**Issue by ddelnano** [ddelnano/terraform-provider-mikrotik#24]
When support was added for the `mikrotik_pool` resource in #22, the documentation was missed.

**Comment by jdelnano** [comment]
Pull request with IP Pool resource documentation created:  https://github.com/ddelnano/terraform-provider-mikrotik/pull/26

**Comment by ddelnano** [comment]
The docs have been updated in v0.4.1 of the provider.
