### ISSUE TITLE
Improve mikrotik command building

### ISSUE THREAD

**Issue by ddelnano** [ddelnano/terraform-provider-mikrotik#30]
The terraform provider manually creates string slices to pass into the `RunArgs` method of the mikrotik client. This results in code that builds strings and is prone to bugs like in #28.

Since the provider is able to decode mikrotik responses into structs, we should provide the ability to marshal a mikrotik command struct into the proper string slice required by the `RunArgs` method.

**Comment by ddelnano** [comment]
I had forgotten that @jdelnano already added this ([source here](https://github.com/ddelnano/terraform-provider-mikrotik/blob/8e786058dd6584e317aa923e7276a096164b26c6/client/client.go#L178)). We will need to use that for all mikrotik commands to prevent these mistakes.

**Comment by ddelnano** [comment]
We should convert all `RunArgs` calls to [Run](https://pkg.go.dev/github.com/go-routeros/routeros#Client.Run) and then update the `Marshal` method to fully format the command string (include the command name `/routing/bgp/instance/add`, etc)

**Comment by jdelnano** [comment]
Closing this with the merging of https://github.com/ddelnano/terraform-provider-mikrotik/pull/36
