### ISSUE TITLE
Enhancement: The ability to assign a new VLAN to an existing Bridge 

### ISSUE THREAD

**Issue by farsonic** [ddelnano/terraform-provider-mikrotik#45]
It would be great to be able to create a new VLAN. For example this is the command I use from the CLI 

add interface=bridge mtu=10000 name=LAB vlan-id=1000

This would be the miminum, plus the ability to enable/disable the interface.

**Comment by maxim-nazarenko** [comment]
Note/label: this issue is about Terraform resource.
