### ISSUE TITLE
Enhancement: Add IP address to an existing interface

### ISSUE THREAD

**Issue by farsonic** [ddelnano/terraform-provider-mikrotik#46]
Is it possible to have the ability to add an IP address (and other parameters) to an existing interface. The command I use from the CLI would be 

add address=192.168.200.1/24 interface=VIP network=192.168.200.0

This would be the minimum requirement, plus the ability to enable/disable the interface through Terraform.

**Comment by OJFord** [comment]
Can be closed due to #53 being merged I believe?

**Comment by ddelnano** [comment]
Oops forgot to close this! Thanks for the reminder
