### ISSUE TITLE
Expand CI to include RouterOS 7 testing

### ISSUE THREAD

**Issue by bennysp** [ddelnano/terraform-provider-mikrotik#48]
I know that RouterOS is not officially released. It is currently in RC2. Will there be plans to update this provider with ROSv7 support?

**Comment by ddelnano** [comment]
Hey @bennysp, absolutely. Our recent improvements in continuous integration (#44) allow us to easily test against different routerOS versions. So I'd like to test against new versions as they come out.

**Comment by ddelnano** [comment]
@bennysp our CI now tests against the latest stable release, v6 beta and v7 beta. v7 is passing for all resources except the bgp ones. If you are not using bgp and want to use v7, the provider should work for you now. I've opened up a new issue to track addressing the bgp problems (#50).

**Comment by bennysp** [comment]
Thanks @ddelnano. That is great news. The BPG is the main one, but this is awesome. Thank you.

**Comment by ddelnano** [comment]
It looks like they completely redesigned how bgp is configured in [v7](https://help.mikrotik.com/docs/display/ROS/ROSv7+Basic+Routing+Examples#ROSv7BasicRoutingExamples-BGPConfiguration). So we will need to implement entirely new resources.

![Screen Shot 2021-09-07 at 6 56 19 PM](https://user-images.githubusercontent.com/5855593/132433711-4a4b1c81-11c1-4c70-9708-ea22726ced6a.png)
