### ISSUE TITLE
add target for darwin_arm

### ISSUE THREAD

**Issue by orenmazor** [ddelnano/terraform-provider-mikrotik#57]
I took a glance and it doesnt look like there's a build target for darwin_arm, only darwin_amd64.

I'm adding a cli configuration to bypass this and run the provider from a locally built copy for now but its a bit of a hack.

**Comment by ddelnano** [comment]
@orenmazor thanks for bringing this up! I've fixed this in #58 and a release that supports darwin/arm64 will be available in v0.8.1.
