### ISSUE TITLE
Error handling should be reviewed in resourceXXXRead() functions

### ISSUE THREAD

**Issue by maxim-nazarenko** [ddelnano/terraform-provider-mikrotik#65]
This issue was revealed while debugging #63

When some resources are read by Terraform, in case of error the `id` is set to `""` (empty string) which is okay in case of `Resource not found` - it means that Terraform should remove it from its state.
But in case of another kind of error, e.g. `Invalid credentials` or `Host not found`, it should not be the case.

The [DnsRecord](https://github.com/ddelnano/terraform-provider-mikrotik/blob/c2a1c2c1e254957f8fb92e328214be2212ee7088/mikrotik/resource_dns_record.go#L63) handles it properly:
```go
if _, ok := err.(*client.NotFound); ok {
	d.SetId("")
	return nil
}
```

but, for example, [Script](https://github.com/ddelnano/terraform-provider-mikrotik/blob/c2a1c2c1e254957f8fb92e328214be2212ee7088/mikrotik/resource_script.go#L104) and [Pool](https://github.com/ddelnano/terraform-provider-mikrotik/blob/c2a1c2c1e254957f8fb92e328214be2212ee7088/mikrotik/resource_pool.go#L56) don't:
```go
if err != nil {
	d.SetId("")
	return nil
}
```

So, in case of wrong credentials, Terraform is trying to delete resources.

It, probably, will be mitigated with #64 , but it is far from even `Ready for review` state.

**Comment by ddelnano** [comment]
The fix will be included in v0.9.1.
