### ISSUE TITLE
Migrate provider documentation to tfplugindocs auto-generation

### ISSUE THREAD

**Issue by maksym-nazarenko** [ddelnano/terraform-provider-mikrotik#82]
In order to use [tfplugindocs](https://github.com/ddelnano/terraform-provider-mikrotik/issues/github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs) to generate [provider docs](https://www.terraform.io/registry/providers/docs), all resources must have `description` field and `exmaple`/`import` file.

This issue will track all available resources and transition progress.
Once all of them are done, `//go:generate...` directive will be introduced to close this issue.

- [x] `provider` (GH-83)
- [x] `mikrotik_bgp_instance` (GH-84)
- [x] `mikrotik_bgp_peer` (GH-85)
- [x] `mikrotik_dhcp_lease` (GH-86)
- [x] `mikrotik_dhcp_server_network` (GH-81)
- [x] `mikrotik_dns_record` (GH-87)
- [x] `mikrotik_ip_address` (GH-88)
- [x] `mikrotik_ipv6_address` (GH-89)
- [x] `mikrotik_pool` (GH-90)
- [x] `mikrotik_scheduler` (GH-91)
- [x] `mikrotik_script` (GH-92)
- [x] introduce new make goal `docs` to trigger `go generate` and build documentation (GH-104)

**Comment by maxim-nazarenko** [comment]
@ddelnano all pending PRs were rebased.
Please, take a look when you have time

**Comment by ddelnano** [comment]
All the PRs are merged, so I think this is complete 🎉. Please close if you agree and really appreciate your work to standardize on the official documentation tool!

**Comment by maksym-nazarenko** [comment]
All the preparation work is done to actually do an auto generation in CI (will be a separate task)
thank you @ddelnano for quick reviews and suggestions 👍
